### ISSUE TITLE
yml file saved in provanance is not working

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#205]
It is supposed to save the environment yml file, but is showing help menu for conda 
http://portal.nersc.gov/project/acme/zhang40/ex_model_to_obs_climo_allsets_fixHadley/prov/environment.yml

**Comment by zshaheen** [comment]
Thanks for looking into this. In [the function that does this](https://github.com/E3SM-Project/e3sm_diags/blob/master/acme_diags/acme_diags_driver.py#L64), the command `conda env export` doesn't seem to be printing the env. It's just a matter of seeing what command will successfully display the env.

**Comment by zshaheen** [comment]
This seems to be fixed in 30dcf16b176516a40e3d92c85510c7c28b8de43e. Previously, all worked when `shell=False`. Then it didn't, so changing it to `shell=True` made it work... until it didn't. Not sure why. Regardless, having `shell=False` is the safer way to do it anyways.

See the results below:
<img width="1161" alt="Screen Shot 2019-05-22 at 4 00 45 PM" src="https://user-images.githubusercontent.com/4239938/58214515-d87f0b80-7caa-11e9-85cc-668ec35b0ef3.png">

@chengzhuzhang, please let me know if this works for you.

**Comment by chengzhuzhang** [comment]
The fix worked! Thanks!
