### ISSUE TITLE
SST_HadISST default diags settings incorrect

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#229]
@chengzhuzhang about 8 months ago, I added `SST_HadISST` to the `lat_lon`,`polar`, and `zonal_mean_xy` `*_model_vs_obs.cfg` files.

<img width="1138" alt="Screen Shot 2019-06-13 at 10 11 21 PM" src="https://user-images.githubusercontent.com/4239938/59484849-4b9e1c80-8e28-11e9-98bd-f2457cdc88bd.png">

It seems like I got the `ref_name` incorrect, since I'm getting the errors:

```
OSError: No file found for HadISST and ANN in /global/project/projectdirs/acme/acme_diags/obs_for_e3sm_diags/climatology/
```

If you look on Cori, there are folders for `HadISST*`:
```
$ ls /global/project/projectdirs/acme/acme_diags/obs_for_e3sm_diags/climatology/HadISST_
HadISST_CL/ HadISST_PD/ HadISST_PI/
```

So the `ref_name` is incorrect, as well as the `reference_name` which should be one of the following:
```
HadISST/OI.v2 (Climatology)
HadISST/OI.v2 (Pre-Indust)
HadISST/OI.v2 (Present Day)
```

Can you fix this issue on master @chengzhuzhang? Thanks!

**Comment by chengzhuzhang** [comment]
@zshaheen I just checked https://github.com/E3SM-Project/e3sm_diags/blob/master/acme_diags/driver/default_diags/lat_lon_model_vs_obs.cfg
This should be an expected behavior. We have four entries in .cfg files. For runs with climatology files, we uses HadISST_CL, HadISST_PD, HadISST_PI. For runs with time-series files, we use HadISST, which allows the user to specify the time period they need for the data. Since the program won't terminate when the key variable is not available, so it is safe to have all four entries in the default lat_lon cfg. When you get the error, did the run stop?

**Comment by zshaheen** [comment]
Okay, I think we can close this issue. I was trying to do that specific run with climo files.

**Comment by zshaheen** [comment]
And no, as expected, the run didn't stop.
