### ISSUE TITLE
Program run 5 times for area_mean_time_series set  when not specifying a season

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#238]
should move seasons out as a set parameter for area_mean_time_series

**Comment by zshaheen** [comment]
@chengzhuzhang It's probably because you we have `seasons = ['ANN', 'DJF', 'MAM', 'JJA', 'SON']`. Basically, since `AreaMeanTimeSeriesParameter` inherits from `CoreParameter`, it'll have [the same values for `granulate` seen here](https://github.com/E3SM-Project/e3sm_diags/blob/master/acme_diags/parameter/core_parameter.py#L69). Also, `AreaMeanTimeSeriesParameter` has `seasons = ['ANN', 'DJF', 'MAM', 'JJA', 'SON']` because `CoreParameter` also has that. When the granulization does its thing, you'll have 5 different parameter objects doing the same thing.

Another way to make your life easier is to remove is to add the following line [underneath this highlighted section in `parameter/area_mean_time_series_parameter.py`](https://github.com/E3SM-Project/e3sm_diags/blob/master/acme_diags/parameter/area_mean_time_series_parameter.py#L9-L12)

```python
self.granulate.remove('seasons')
```

This will just remove `seasons` as a value to granulate over.

**Comment by chengzhuzhang** [comment]
fixed in https://github.com/E3SM-Project/e3sm_diags/pull/248
