### ISSUE TITLE
e3sm_diags in unified_env missing plots - mpi4py issue

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#242]
@xylar I'm testing e3sm_diags on compy. It occurs to me that some diagnostics plots are not generated under unified_env_py3.7, as following:
https://compy-dtn.pnl.gov/zhan429/lat_lon_demo/viewer/latitude-longitude/index.html
(e.g., SOLIN global ceres_ebaf_toa_v2.8)

However when I tried to run e3sm_diags in its own conda environment (1.7.1). All plots are generated, see following:
https://compy-dtn.pnl.gov/zhan429/lat_lon_demo_1.7.1_py3/viewer/latitude-longitude/index.html

The error I have when running from e3sm_unified_py3.7:
```
Error in acme_diags.driver.lat_lon_driver
Traceback (most recent call last):
  File "/compyfs/software/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 211, in run_diag
    single_result = module.run_diag(parameters)
  File "/compyfs/software/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/acme_diags/driver/lat_lon_driver.py", line 168, in run_diag
    region, mv1, mv2, land_frac, ocean_frac, parameter)
  File "/compyfs/software/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/acme_diags/driver/utils/general.py", line 143, in select_region
    var1, land_ocean_frac, low_limit=region_value)
  File "/compyfs/software/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/acme_diags/driver/utils/general.py", line 199, in mask_by
    var = copy.deepcopy(input_var)
  File "/compyfs/software/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/compyfs/software/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/site-packages/numpy/ma/core.py", line 6045, in __deepcopy__
    copied.__dict__[k] = deepcopy(v, memo)
  File "/compyfs/software/e3sm-unified/base/envs/e3sm_unified_1.2.6/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle mpi4py.MPI.Intracomm objects
```
Any suggestion on trouble shooting this issue?

@golaz Since we are having this issue, in the quick guide for `compy` I recommended e3sm_unified python2.7, however it only have e3sm_diags 1.6.1 which misses some new variables and bug fixes. Alternatively, you can use following command to install e3sm_diags1.7.1
```
conda create -n e3sm_diags_v1.7.1_py3 e3sm_diags python=3 -c e3sm -c conda-forge -c cdat
```

**Comment by xylar** [comment]
@chengzhuzhang, I'm happy to help debug.  I just ran:
```bash
source /compyfs/software/e3sm-unified/load_latest_e3sm_unified.sh
e3sm_diags --no_viewer --sets 'lat_lon' --case_id 'CERES-EBAF-TOA-v4.0' --variables 'SOLIN' --ref_name 'ceres_ebaf_toa_v4.0' --reference_name 'CERES-EBAF' --seasons 'ANN' --contour_levels '0' '50' '100' '150' '200' '250' '300' '350' '400' '450' --diff_levels '-5' '-4' '-3' '-2' '-1' '-0.5' '0.5' '1' '2' '3' '4' '5' --run_type 'model_vs_obs' --regions 'global' --regrid_tool 'esmf' --regrid_method 'conservative' --main_title 'SOLIN ANN global' --backend 'mpl' --output_format 'png' --canvas_size_w '1212' --canvas_size_h '1628' --figsize '8.5' '11.0' --dpi '150' --arrows --test_name '20161118.beta0.FC5COSP.ne30_ne30.edison' --test_colormap 'cet_rainbow.rgb' --reference_colormap 'cet_rainbow.rgb' --diff_title 'Model - Observation' --diff_colormap 'diverging_bwr.rgb' --multiprocessing --num_workers '40' --granulate 'variables' 'seasons' 'regions' 'plevs' --selectors 'sets' 'seasons' --reference_data_path '/compyfs/e3sm_diags_data/obs_for_e3sm_diags/climatology/' --results_dir '/compyfs/www/asay932/lat_lon_demo_1.7.1_py3' --test_data_path '/compyfs/e3sm_diags_data/test_model_data_for_acme_diags/climatology/'
```
and it appears to have run without a hitch, producing:
```
$ ls /qfs/people/asay932/compyfs/www/asay932/lat_lon_demo_1.7.1_py3/lat_lon/CERES-EBAF-TOA-v4.0

ceres_ebaf_toa_v4.0-SOLIN-ANN-global.json
ceres_ebaf_toa_v4.0-SOLIN-ANN-global.png
```

Could you give me an exact set of instructions so I can reproduce the error?

**Comment by chengzhuzhang** [comment]
@xylar Thank you very much for checking! I tried the exact same run just now and the variables missing shown up, I think it is just one-time glitch on Compy. 

However The error `TypeError: can't pickle mpi4py.MPI.Intracomm objects` is still there. It must be an independent error. There are some missing variables that in the unified env when comparing to the run using e3sm_1.7.1 stand alone env, e.g. CRU temperature and SST are missing. Following command can reproduce the error in unified env py3.7:
```
e3sm_diags --no_viewer --sets 'lat_lon' --case_id 'CRU_IPCC' --variables 'TREFHT' --regions 'land_60S90N' --ref_name 'CRU' --reference_name 'CRU Global Monthly Mean T Land' --seasons 'ANN' --contour_levels '-35' '-30' '-25' '-20' '-15' '-10' '-5' '0' '5' '10' '15' '20' '25' '30' '35' '40' --diff_levels '-15' '-10' '-5' '-2' '-1' '-0.5' '-0.2' '0' '0.2' '0.5' '1' '2' '5' '10' '15' --run_type 'model_vs_obs' --regrid_tool 'esmf' --regrid_method 'conservative' --main_title 'TREFHT ANN land_60S90N' --backend 'mpl' --output_format 'png' --canvas_size_w '1212' --canvas_size_h '1628' --figsize '8.5' '11.0' --dpi '150' --arrows --test_name '20161118.beta0.FC5COSP.ne30_ne30.edison' --test_colormap 'cet_rainbow.rgb' --reference_colormap 'cet_rainbow.rgb' --diff_title 'Model - Observation' --diff_colormap 'diverging_bwr.rgb' --multiprocessing --num_workers '40' --granulate 'variables' 'seasons' 'regions' 'plevs' --selectors 'sets' 'seasons' --reference_data_path '/compyfs/e3sm_diags_data/obs_for_e3sm_diags/climatology/' --results_dir '/compyfs/www/zhan429/lat_lon_demo_1.7.1_py3' --test_data_path '/compyfs/e3sm_diags_data/test_model_data_for_acme_diags/climatology/' 
```
Any variables that need to be masked (e.g. land only temperature) are missing. The `mask by` function was inherited from an old package, we will need to modernize it.

**Comment by xylar** [comment]
@chengzhuzhang, I think making a deep copy of an MPI Intracomm is likely not supported, see this comment from 2 years ago on the same error message:
https://github.com/dfm/emcee/issues/229#issuecomment-336469925

I think the solution for getting rid of that error message would be to remove whatever MPI info you are trying to deep copy on this line:
https://github.com/E3SM-Project/e3sm_diags/blob/master/acme_diags/driver/utils/general.py#L200

I'm not sure why it works in your other envrionment, because it really just shouldn't work at all.  Unless the MPI info is stripped out for some reason with certain package versions and not others.  I don't really know enough about e3sm_diags to debug this further.  The strategy I would suggest would be to find out which packages are different between your test environment and e3sm_unified, and see which might related to this issue (e.g. having something to do with mpi or mpi4py).

If you can come up with something more specific for me to look into (e.g. trying e3sm_unified with a specific set of alternative packages), I'm happy to do so.

**Comment by xylar** [comment]
If it would be helpful, maybe we could have a quick phone call about this.

**Comment by xylar** [comment]
Also, could you try creating an environment with the following and see if you end up with the same errors as on e3sm_unified?

```
conda create -n e3sm_diags_v1.7.1_py3.7 e3sm_diags python=3.7 -c e3sm -c conda-forge -c cdat/label/v81
```
Your command above installs a python 3.6, not a python 3.7, environment.  It uses some older versions of cdat packages (the newest are under the v81 label).  Either or both of these may be related.  If that doesn't work as expected, maybe try forcing a python 3.6 install but using the newest cdat:

```
conda create -n e3sm_diags_v1.7.1_py3.6 e3sm_diags python=3.6 -c e3sm -c conda-forge -c cdat/label/v81
```
That would tell you whether python 3.7 or the latest cdat is more likely the cause.  There is no way to install the older cdat packages with python 3.7, as far as I know, because they simply weren't built for it.

See if you can make some headway with these suggestions and give me a call at LANL if not.

**Comment by xylar** [comment]
A further update.  I tried the command you provided above (https://github.com/E3SM-Project/e3sm_diags/issues/242#issuecomment-520294464).  I am able to reproduce the problem in e3sm-unified 1.2.6 but the test ran successfully with all 3 conda environments I created (your suggestion here https://github.com/E3SM-Project/e3sm_diags/issues/242#issue-479205422) and my two from above.

Curious!

**Comment by chengzhuzhang** [comment]
Thank you for trouble-shooting! It's truly mysterious that the problem only occurs in unified 1.2.6... I'm on travel this week, will do more testing/trouble-shooting in a later time. I have a separate question. To use processflow, I should activate  e3sm-unified 1.2.6 py2, right? Since, python 3 has not been supported.

**Comment by xylar** [comment]
> I have a separate question. To use processflow, I should activate e3sm-unified 1.2.6 py2, right? Since, python 3 has not been supported.

No, I don't use it. But, yes, that's correct.  You have to use the py2.7 environment because py3 support is still under development.

**Comment by xylar** [comment]
I did one last experiment where I made a brand new e3sm_unified 1.2.6 py3.7 environment, just to see if maybe some package got updated in the last few weeks and that fixed the problem.  No such luck.  So it must be a package we're pinning to a different version than what comes when we install e3sm_diags on its own.  I'll keep trying things out to see if I can figure out which package it is, but it'll be a few days before I have time to come back to this.  I guess the workaround for now is not to use the e3sm-unified environment :-(

**Comment by xylar** [comment]
@chengzhuzhang, I know you're on travel but I wanted to give you an update on this that might help to debug it further.  I created an environment like so:
```
conda create -n test1 -c e3sm -c conda-forge -c cdat/label/v81 e3sm_diags python=3.7
```
I created an identical environment but with `mpi4py` added:
```
conda create -n test2 -c e3sm -c conda-forge -c cdat/label/v81 e3sm_diags python=3.7 mpi4py
```
The example command you gave me above works fine in `test1` but fails with the error about pickling `mpi4py` in `test2`.  So it appears that a `mpi4py.MPI.Intracomm` object gets added to instances of `cdms2.tvariable.TransientVariable` when `mpi4py` is present, and these objects can't be duplicated with `deepcopy`.

Looking at https://github.com/CDAT/cdms/blob/master/Lib/tvariable.py#L30, it's clear that `TransientVariable`s are quite different in general if `mpi4py` is present compared to if it's not.  I'm slightly concerned that the difference in behavior will go well beyond the `deepcopy` and that `cdms2` assumes you want to use MPI simply because `mpi4py` is present in the environment.  But I don't know enough about the details and it would be worth working with the CDAT folks on that.

If the `deepcopy` really is the only issue, it might still be necessary to work with the CDAT folks to find out how to do a safe equivalent of `deepcopy` of `TransientVariable` objects when `mpi4py` is present.

@doutriaux1 or @dnadeau4, do either of you have thoughts on this?

**Comment by xylar** [comment]
One more comment, there are three places where `deepcopy` is called:
```
$ grep -r deepcopy
acme_diags/driver/utils/general.py:    var = copy.deepcopy(input_var)
acme_diags/run.py:            parent = copy.deepcopy(parent)
acme_diags/derivations/acme.py:    var = copy.deepcopy(input_var)
```
and it seems likely that at least 2 of these, maybe all 3 would need a different treatment unless the MPI-specific stuff can be removed on the `cdms2` side instead.

**Comment by zshaheen** [comment]
@xylar, I'm very happy that you're helping out with some stuff. I was worried what would happen after my departure. Thanks for doing so! :)

@chengzhuzhang You might want to try running the diags the "old way", without using `from acme_diags.run import runner`. So for example: `e3sm_diags -p params.py`. This will help you determine if the issue is caused by where `copy.deepcopy` is being done in `acme_diags/run.py` as Xylar showed.

**Comment by chengzhuzhang** [comment]
@xylar Thank you for helping isolate the problem! The section of codes you pointed out in `cdms` should have caused the issue.
```
HAVE_MPI = False
try:
    from mpi4py import MPI
    HAVE_MPI = True
except BaseException:
    pass
```
It does seem like these codes are only tested in serial.  @dnadeau4 and @doutriaux1 Should we create an issue and review it?

At the same time I will test PR #243 to make sure things are all working properly. @xylar Appreciate it very much!
