### ISSUE TITLE
Occasional core dumps on compy

### ISSUE THREAD

**Issue by golaz** [E3SM-Project/e3sm_diags#277]
When running E3SM Diags as a batch job on compy nodes, E3SM Diags will occasionally fail with a core dump. The batch job doesn't actually stop until it times out. The log file doesn't show any errors.

Unclear whether this is a compy issue (bad node?) or an E3SM Diags issue. Last time it happened to me was on compute node n0001.

**Comment by chengzhuzhang** [comment]
It seem like @oksanaguba had experienced similar issue on compy. @forsyth2 we may need to design a test to identify if this is e3sm_diags issue or not.

**Comment by forsyth2** [comment]
@chengzhuzhang what would the test look like? Determine the system (e.g., Cori, Compy) we're running on, launch a batch job on that system, and check for successful completion? That would just tell us if the error is occurring; we really need to get some sort of log to see why the core dumped.

We might also want to keep this test separate from the main test suite since I imagine queueing for nodes may cause a considerable delay.

**Comment by chengzhuzhang** [comment]
I would think we can have a specific test for Compy to lauch multiple jobs and check for successful rate and also figure out why the core dumped if  the job failed. And yes, it's good to have the test separate from the main test suite..

**Comment by forsyth2** [comment]
@golaz can you post or email me the batch script you're running? I can use that as a starting point for writing a test.

**Comment by golaz** [comment]
@forsyth2 : here is an example. Submit it to the queue using sbatch.

[e3sm_diags_180x360_aave_model_vs_obs_1981-2000.bash.txt](https://github.com/E3SM-Project/e3sm_diags/files/4237450/e3sm_diags_180x360_aave_model_vs_obs_1981-2000.bash.txt)

**Comment by chengzhuzhang** [comment]
It seems like a one-off problem. A full set run on Compy is implemented for testing.
