### ISSUE TITLE
post.py failed on cori

### ISSUE THREAD

**Issue by xuezhengllnl** [E3SM-Project/e3sm_diags#284]
I followed the steps on https://github.com/E3SM-Project/e3sm_diags/issues/282 and installed an e3sm_diags_env_dev on cori.
Here are the error messages when I was trying to run post.py. Does anyone know how to solve this sbatch error? Thank you! 

`python ~/E3SM_post/PreAndPostProcessingScripts/postprocessing_bundle/v2/post.py -c 20190807.DECKv1b_P1_SSP5-8.5.ne30_oEC.cori-knl.cfg 
Configuration file validation passed
climo_180x360_aave_2016-2035
...
Problem submitting script /global/cscratch1/sd/xzheng/Data/20190807.DECKv1b_P1_SSP5-8.5.ne30_oEC.cori-knl/post/scripts/climo_180x360_aave_2016-2035.bash
b'sbatch: error: Job request does not match any supported policy for cori\nsbatch: error: Batch job submission failed: Unspecified error\n'
Traceback (most recent call last):
  File "/global/homes/x/xzheng/E3SM_post/PreAndPostProcessingScripts/postprocessing_bundle/v2/post.py", line 56, in <module>
    if config['climo']['active']: climo(config, scriptDir)
  File "/global/u2/x/xzheng/E3SM_post/PreAndPostProcessingScripts/postprocessing_bundle/v2/climo.py", line 68, in climo
    jobid = submitScript(scriptFile)
  File "/global/u2/x/xzheng/E3SM_post/PreAndPostProcessingScripts/postprocessing_bundle/v2/utils.py", line 78, in submitScript
    raise Exception
Exception
`

**Comment by golaz** [comment]
@xuezhengllnl : It appears that the script was generated, but could not be submitted. Can you change permissions on your script

`/global/cscratch1/sd/xzheng/Data/20190807.DECKv1b_P1_SSP5-8.5.ne30_oEC.cori-knl/post/scripts/climo_180x360_aave_2016-2035.bash`

so I can take a look at what might have gone wrong?

I will close this issue since it is not related to e3sm_diags.
