### ISSUE TITLE
Updates docs on examples

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#311]
Most of the examples use the "old" method of creating the parameter file instead of setting the params via the api. Although they should still work, the presence of these files may confuse the users when searching. This may relate to another issue filed under documentation label: https://github.com/E3SM-Project/e3sm_diags/issues/299

https://e3sm-project.github.io/e3sm_diags/docs/html/examples/model_climo-vs-obs_climo.html

**Comment by forsyth2** [comment]
Both the examples (https://github.com/E3SM-Project/e3sm_diags/tree/master/examples) in the `master` branch and corresponding docs in the `gh-pages` branch  should be updated? In that case, we should make these changes before implementing #299, so that the examples will be correct in the docs for the latest release (which I assume is the one following the current one v2.1.1).

**Comment by chengzhuzhang** [comment]
Good point. I'm not sure if we should keep two copies of examples, which are almost identical. We had plan to reduce to one copy but never get around to do so.  How about let's just update the ones on `master` (adding new ways of running, while keep the old ways which were still compatible) and the documentation can point to the files on master?

**Comment by forsyth2** [comment]
Fixed by #341 and #340.
