### ISSUE TITLE
Automate building and serving docs

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#377]
I noticed that we have to run `make html` to build `docs`, then push the contents of our `docs` folder. I recognize that this is a limitation with GitHub pages, which requires the static build to already exist so content can be served. 

However, if there is a way to automate building docs, we can avoid pushing generated content and focus on code changes. It will make it easier for us to do PR reviews using the 'Files Changed' tool whenever there are doc updates, especially if we have docs served through `master` in the future.

Options:
1. Use CI/CD on `master` to build docs on `gh-pages` branch
2. Use docs directory on `master` to render GitHub Pages - need to generate and commit docs as apart of local workflow (current process with `gh-pages` branch)

Leaning towards option 1 since that fits into the current project workflow.

Alternative:
ReadTheDocs automatically builds and serves docs.

Resources:
- https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
- https://docs.readthedocs.io/en/stable/builds.html

**Comment by chengzhuzhang** [comment]
I also feel the documentation update process has been cumbersome. Not sure if we have to switch to ReadTheDocs to automate building.

**Comment by xylar** [comment]
In [MPAS-Analysis](https://github.com/MPAS-Dev/MPAS-Analysis/) and other MPAS-related repos I manage, I found that ReadTheDocs gave us a lot of trouble.  Their CI has very little memory, which means that it's difficult to impossible to build a conda package if you use the [API autogeneration](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) tools from sphinx (which I highly recommend!).  I found it wasn't too hard to just add building and uploading the documentation as part of our Travis CI (and later as part of Azure Pipelines when Travis gave us some trouble).

I would highly recommend that path over ReadTheDocs since you're running CI anyway.  As @tomvothecoder's link indicates, the same is possible on CircleCI.

Also, if you're not using a separate branch (nearly always `gh-pages`) for the documentation, I recommend that, too.  As @tomvothecoder says, having changes in the rendered documentation show up in code branches is somewhere between distracting and downright confusing.
