### ISSUE TITLE
Update conda dev environment dependencies

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#393]
Building a conda environment with `e3sm_diags_env_dev.yml` in its current state on Linux machines causes the following issue:

![image](https://user-images.githubusercontent.com/25624127/109083853-8b1fa180-76bb-11eb-8659-a0cb6210e1db.png)

There seems to be mismatching dependencies resulting in conflicts.

The solution would be to create a conda environment with the base dependencies for the dev environment, then export it to the respective .yml file.

EDIT: New proposed solution https://github.com/E3SM-Project/e3sm_diags/pull/394#issuecomment-786020056

**Comment by xylar** [comment]
I know you all do like having the yaml files for your development environments but I think this is a really fragile way of defining things.  For MPAS-Analysis, we have a development environment just defined as the command for creating the env:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create -n mpas-analysis python=3.8 numpy scipy "matplotlib>=3.0.2" \
    netCDF4 "xarray>=0.14.1" dask bottleneck lxml "nco>=4.8.1" pyproj \
    pillow cmocean progressbar2 requests setuptools shapely "cartopy>=0.18.0" \
    cartopy_offlinedata "geometric_features>=0.1.13" gsw "pyremap<0.1.0" \
    "mpas_tools>=0.0.15" pandas python-dateutil six
conda activate mpas-analysis
```
This way, you're only constraining some relevant packages rather than pinning every single one.

If you really want to preserve an environment that others should use exactly as it is, the only real way to do that is some form of tarring up the packages, e.g.:
https://conda.github.io/conda-pack/
But I don't think that's an appropriate approach for a development environment.  That would be more for preserving a production environment so you could reproduce the results exactly at a later point.

**Comment by tomvothecoder** [comment]
@xylar Thanks for looking into this.

I actually suggested a solution for pinning only the base dependencies for prod and dev environments, which reduces the length and complexity of the yml files and the need to split files by OS. As you mentioned, pinning every single dependency has a high chance of failure and isn't necessary. 

Here's my solution for reference.
https://github.com/E3SM-Project/e3sm_diags/pull/394#issuecomment-786020056

**Comment by xylar** [comment]
I agree, that's going to make your lives a lot easier.
