### ISSUE TITLE
rename `acme_diags` to `e3sm_diags`

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#458]
I think it would make sense to rename the `acme_diags` package to `e3sm_diags`.  You could also continue to make an `acme_diags` shadow package that points to `e3sm_diags` but is deprecated and will be removed in a future release.  Here is an example from the `pyevtk` project, which has a deprecated `evtk` package:
https://github.com/pyscience-projects/pyevtk/blob/master/evtk/__init__.py

**Comment by chengzhuzhang** [comment]
Hey @xylar, thank you for bringing this up and  pointing to the example. I didn't know a good solution to do renaming without disturbing current use of our repo. We will look into it and try renaming in the next release.

**Comment by tomvothecoder** [comment]
PyCharm will be great for project restructuring because of its indexing and refactoring capabilities. It's very easy to rename, move, and delete files/directories in PyCharm. For example, when you rename a directory, there will be a prompt to confirm updating the old directory references (such as Python imports and comments) throughout the project. This is much safer than doing a manual find and replace.

I'll give this a shot for the next release candidate.

**Comment by xylar** [comment]
@tomvothecoder, that's great.  I agree that pycharm is a great way to go.

I don't know if you all want to take care of this for the current release or wait until the next one.  I'm fine either way.

**Comment by zshaheen** [comment]
If you do this @tomvothecoder, you'll be our hero! This has been an annoyance (for me that is) since the name change. I had no idea there was a less-painful way to do this!

**Comment by tomvothecoder** [comment]
@xylar I think holding off for the next release will be good since it might introduce a large changeset during the RC phase.

@zshaheen It will be a nice improvement, and hopefully less confusing! 😄
