### ISSUE TITLE
Consider moving development environment to python 3.9

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#470]
It would be great if your development environment were one python version ahead of E3SM-Unified, which is going to be deployed on supported machines with python 3.8 for the 1.5.0 release.   This way, you would see any issues with python 3.9 well before E3SM-Unified moves to this version.  In general, my understanding is that it is a good practice to develop with the latest supported python version.

**Comment by xylar** [comment]
In general, I think it's a risky practice to pin packages in your development environment to older versions because you will tend not to notice when the newest versions are not compatible with e3sm_diags until either when you're testing a release (pretty late) or after a release (too late!).

**Comment by tomvothecoder** [comment]
> In general, I think it's a risky practice to pin packages in your development environment to older versions because you will tend not to notice when the newest versions are not compatible with e3sm_diags until either when you're testing a release (pretty late) or after a release (too late!).

It has been a lack of maintaining the conda env dependencies, rather than intentionally pinning to older versions. 

I usually automate this process using a dependency monitoring tool (like [PyUp](https://pyup.io/)) to open PRs that include updates for the latest versions. I'm still looking for a dependency monitoring tool that supports Anaconda!

Otherwise, we'd have to manually update the versions of the dependencies which isn't fun.
