### ISSUE TITLE
using already column-integrated burdens instead of 3D profiles for aerosol diagnostics

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/e3sm_diags#681]
Following up from https://acme-climate.atlassian.net/wiki/spaces/CM/pages/3749576957/2023-04-17+Coupled+Model+-+Meeting+notes. 

Following https://github.com/E3SM-Project/e3sm_diags/pull/676, we should simplify the routine for the burden diags by using already integrated quantities. The details of which are in this comment: https://github.com/E3SM-Project/e3sm_diags/pull/676#issuecomment-1449131478. 

For now, I recommend the following:
- use the `BURDEN` terms if available; or else,
- fail silently or print 0s for the table.

This way, e3sm_diags works as expected and the end user is responsible for ensuring `BURDEN` terms are included in h0 files. In the future we could consider adding these `BURDEN` variables (which are 2D) to the standard output, as opposed to the `Mass_` ones (which are 3D).

Copying  @chengzhuzhang, @golaz, @susburrows, and @kaizhangpnl for awareness. I could submit a PR with the edits in the near future (and with help from Jill, we could finalize this).

**Comment by kaizhangpnl** [comment]
I think BURDEN fields do not include cloud-borne aerosols, but Mass_XYZ fields do. For the aerosol mass budget, we need both interstitial and cloud-borne aerosol mass.

**Comment by chengzhuzhang** [comment]
@mahf708 thank you for opening up this issue and willing to take on this task!
The proposed solution is good! It sounds like we will first verify the consistence between BURDEN and MASS variables, and to make sure we have everything needed to be taken into account in these terms as @kaizhangpnl suggested.

**Comment by susburrows** [comment]
Thanks for taking the initiative to lead this task, @mahf708 !

**Comment by susburrows** [comment]
I looked through the code and it appears @kaizhangpnl is correct that the BURDEN diagnostics include only the interstitial aerosol (and not the cloud-borne aerosol).  The specmmr term in the BURDEN summation (line 789 in [modal_aer_opt.F90](https://github.com/E3SM-Project/v3atm/blob/NGD_v3atm/components/eam/src/physics/cam/modal_aer_opt.F90)) is obtained at line 771 via:
call rad_cnst_get_aer_mmr(list_idx, m, l, 'a', state, pbuf, specmmr)

The 'a' argument will result in retrieving only interstitial aerosol.

I suspect the reason for this is that this diagnostic term is being calculated in the code that handles radiative interactions, and since the cloudborne aerosol does not directly interact with radiation, it is also not being counted in this diagnostic.

But for mass budgets, we obviously want both the cloudborne and interstitial terms.  It would be pretty easy to add the lines to the code to calculate an additional set of diagnostics that includes both the interstitial and cloudborne terms.  Are you willing to take this on, @mahf708 ?

**Comment by susburrows** [comment]
I think the more conservative option would be to introduce new diagnostic terms that include either the cloudborne portion or both the cloud borne and interstitial portions.

The objective of the exercise is to reduce the amount of output that is required for the production runs to only what is used in e3sm_diags and other diagnostic tools.  In that spirit, the minimal output would be a burden term for each species that includes both the interstitial and cloudborne components.

I like your idea to do this by column-integrating the Mass_ terms in mo_chem_diags.F90, but since those terms are actually only calculated (in addition to being only outputted) when history_aerosol is true, it looks like that won't work for these diagnostics, which we want to have turned on in all production runs.

@kaizhangpnl : do you have any further thoughts on the best way to approach this?

**Comment by kaizhangpnl** [comment]
> Hmm... that's kinda weird. Any historical reason why they were treated differently? Also,
> 
> * how different would you expect the values to be? ±10% or more?

I think these burden fields were designed to be calculated consistently with the aerosol optical properties to estimate the mass extinction coefficient (AOD/BURDEN), which is a variable related to the direct aerosol effect. As Susannah mentioned, only the interstitial aerosols are counted for the radiative transfer calculation, so the burden fields are calculated/sampled similarly. 

The cloud-borne aerosol mass is only a small fraction of the total (interstitial + cloud-borne) mass (e.g., ~3% for sulfate). So using the interstitial aerosol burden will provide an estimate that is pretty close to the accurate one. 

BTW, it is more accurate to use the online burden output, rather than calculating the burden offline using the mean 3D mass fields. The difference shown in Naser's table (https://github.com/E3SM-Project/e3sm_diags/pull/676) also includes the error caused by using the mean 3D mass and PS to calculate the burden.

**Comment by kaizhangpnl** [comment]
> The objective of the exercise is to reduce the amount of output that is required for the production runs to only what is used in e3sm_diags and other diagnostic tools. In that spirit, the minimal output would be a burden term for each species that includes both the interstitial and cloudborne components.
> 
> I like your idea to do this by column-integrating the Mass_ terms in mo_chem_diags.F90, but since those terms are actually only calculated (in addition to being only outputted) when history_aerosol is true, it looks like that won't work for these diagnostics, which we want to have turned on in all production runs.
> 
> @kaizhangpnl : do you have any further thoughts on the best way to approach this?
> 
> [EDITED to remove first sentence after I realized it did not make sense]

I think the proposed approach (column-integrating the Mass_ terms) is good. I guess Chris will modify the overall output control and the aerosol diagnostics output can follow the new example.

**Comment by susburrows** [comment]
@mahf708 that sounds good to me.  @kaizhangpnl and @chengzhuzhang , does it sound good to you also?

**Comment by kaizhangpnl** [comment]
Yes. I don't have a preference on this.

**Comment by susburrows** [comment]
@mahf708 just to clarify, though, you will keep the existing BURDEN accumulators as-is, and add new accumulators for the total burden, correct?  I think we should not change the existing accumulator since it may be used elsewhere (or in analysis scripts somewhere).

**Comment by susburrows** [comment]
@mahf708 I think you can go ahead and make the E3SM code changes.

**Comment by susburrows** [comment]
@mahf708 , do I understand correctly that the MASS_ implementation in e3sm_diags is using monthly-averaged output of the MASS_ and pressure fields?  If that is the case, we should expect that diagnostic to include some errors; the ABURDEN calculation should be more exact.  I think these differences are in the range that can be explained by this type of averaging error.

**Comment by susburrows** [comment]
@mahf708 : it could also be helpful to separate the stratospheric and tropospheric sulfate aerosol, as suggested by @kaizhangpnl last week.  The tropospheric sulfate aerosol should be an apples-to-apples comparison with the multi-model benchmarks from Aerocom, and we can probably identify different, separate benchmarks for the stratospheric sulfate.

Could we easily separate these?  At least crudely, by doing a separate set of budget diagnostics for sulfate in the 5th mode?

**Comment by kaizhangpnl** [comment]
> If @kaizhangpnl or @susburrows could check if the burden1, burden2, etc. calculations are done correctly, then I can easily separate the fifth mode. I am just not confident enough in what's happening, that's why I didn't edit these burdens to begin with. I think they largely make sense after a more careful reading of the code, but I cannot be sure myself...

I think the total BURDEN fields for individual modes are calculated correctly, so we can obtain the burden for mode 5. If there is only sulfate in this mode and the source/sink terms are available, the mass budget for stratospheric sulfate can be estimated. However, I am not sure whether we can diagnose the stratospheric sulfate lifetime by using only the wet+dry removal terms (similarly for tropospheric sulfate), since there might be conversion between a5 and other modes containing sulfate that also should be considered as a sink term. It would be better to ask the stratospheric sulfate developer to provide some suggestions.
