### ISSUE TITLE
Refine of 4 yaml files in `conda-env`

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#695]
@tomvothecoder and @chengzhuzhang, I'd like to have a discussion about the purposes of the 4 different yaml files here.

### `ci.yml`
I think `ci.yml` probably needs more constraints on packages than it has in this PR, and certainly more than it had before this PR.  There's presumably a minimum `numpy`, `xarray`, etc. that `e3sm_diags` requires.

### `dev.yml`
I think `dev.yml` is too constrained.  I understand that the purpose is for everyone to be testing with the exact same versions of all the important packages but the reality of this ends up being that testing isn't happening with the newest available versions and thus problems (like the recent `numpy.int` and `numpy.float` issues) may not be noticed during developer testing and instead emerge in E3SM-Unified testing or after a release has happened.  I would instead suggest having `dev.yml` be the same as `ci.yml` with the additional dependencies needed for development.

### `docs.yml`
My only question here is whether the benefits of pinning to specific package versions (e.g. stability) outweigh the advantages of getting the latest versions instead.  This puts extra burden on developers to update the package versions over time.

### `prod.yml`
My question here is whether there is a clear advantage in folks using the same exact python and pip version to the patch level, and whether this is worth the effort from developers to keep it updated.  It seems easier to just put in the documentation:
```
conda env create -y -n e3sm_diags_env e3sm_diags
conda activate e3sm_diags_env
```

By the way there's an inconsistency between the name in the yaml file:
https://github.com/E3SM-Project/e3sm_diags/blob/main/conda-env/prod.yml#L2
and the docs:
https://e3sm-project.github.io/e3sm_diags/_build/html/main/install.html#a-latest-stable-release
And also the command in the docs should be:
```
conda env create -f prod.yml
```
without the `conda-env/` directory.

**Comment by tomvothecoder** [comment]
Thanks for opening up this discussion. Overall, I agree with your suggestions to simplify the conda environments yml files.
This will also reduce my workload because I think I'm the only one really maintaining these yml files across all of the repos I work on.

> ### `dev.yml`
> 
> I think `dev.yml` is too constrained. I understand that the purpose is for everyone to be testing with the exact same versions of all the important packages but the reality of this ends up being that testing isn't happening with the newest available versions and thus problems (like the recent `numpy.int` and `numpy.float` issues) may not be noticed during developer testing and instead emerge in E3SM-Unified testing or after a release has happened. I would instead suggest having `dev.yml` be the same as `ci.yml` with the additional dependencies needed for development.

The original intent was to have developers use the same exact dependency versions during development (which is critical in some software dev scenarios). In this case it makes sense for us to loosen up the `dev.yml` constraints. Since `e3sm_diags` is included in E3SM Unified and follows a release schedule, we have to ensure its dependencies are compatible with the dependencies of the other packages (especially not at the last second before releasing packages).

> ### `docs.yml`
> 
> My only question here is whether the benefits of pinning to specific package versions (e.g. stability) outweigh the advantages of getting the latest versions instead. This puts extra burden on developers to update the package versions over time.

I agree here. We don't have enough resources and/or interest from people to maintain the yml files.

> ### `prod.yml`
> 
> My question here is whether there is a clear advantage in folks using the same exact python and pip version to the patch level, and whether this is worth the effort from developers to keep it updated. It seems easier to just put in the documentation:
> 
> ```
> conda env create -y -n e3sm_diags_env e3sm_diags
> conda activate e3sm_diags_env
> ```

This file can probably be removed since nobody probably uses this (my thought a long time ago).

**Comment by tomvothecoder** [comment]
If we're all on the same page, let's convert this to an issue and I can work on it.
