### ISSUE TITLE
[Feature]: CDAT Migration: Add support for opening multiple time series datasets

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#861]
### Is your feature request related to a problem?

The CDAT codebase supports XML files to open up multiple time series datasets. The `cdat-migration-fy24` branch uses `xc.open_dataset()` for single variables that don't need to be derived.

- Zppy specifies input paths as directories of `.nc` files (related [comment](https://github.com/E3SM-Project/zppy/pull/598#issuecomment-2387139221))
- There might be some cases where variables are split up across multiple files and need to be concatenated as a single dataset object. 

### Describe the solution you'd like

Update `_get_time_series_dataset_obj()` to use `xc.open_mfdataset()`

https://github.com/E3SM-Project/e3sm_diags/blob/22cd0f569e7df4be147a8fe6fae3e00d5aeb9d8c/e3sm_diags/driver/utils/dataset_xr.py#L1035-L1037

**Comment by forsyth2** [comment]
> Zppy specifies input paths as directories of `.nc` files

Just to elaborate a bit:

- The core of https://github.com/E3SM-Project/zppy/pull/598 is the `bash` [file change](https://github.com/E3SM-Project/zppy/pull/598/files#diff-ed02c5b26bf8ed8e97148b4f81cfdca9afc1706855f5a7aba9e0b7f3c47cee52)
- That takes `zppy` from A) concatenating variables into a txt file and then using `cdscan` to create an xml file to B) taking an entire directory of `nc` files. I.e., "process all the variables in this directory" rather than "process all the variables I listed in this file".
- This is incompatible with how Diags (on `main`) currently functions, which is why https://github.com/E3SM-Project/zppy/pull/598 can't be merged into zppy's `main` until Diags has completed its CDAT migration.

**Comment by tomvothecoder** [comment]
Closed by #866
